### ISSUE TITLE
Traceback errors: Incomplete Read

### ISSUE THREAD

**Issue by bsyu1125** [SLUGIS/incidentSpreadsheet#10]
```
Traceback (most recent call last):
  File "send.py", line 120, in <module>
    main()
  File "send.py", line 107, in main
    values = wks.get_all_values()
  File "/usr/local/lib/python2.7/dist-packages/gspread/models.py", line 339, in get_all_values
    cells = self._fetch_cells()
  File "/usr/local/lib/python2.7/dist-packages/gspread/models.py", line 226, in _fetch_cells
    feed = self.client.get_cells_feed(self)
  File "/usr/local/lib/python2.7/dist-packages/gspread/client.py", line 242, in get_cells_feed
    return ElementTree.fromstring(r.read())
  File "/usr/lib/python2.7/httplib.py", line 541, in read
    return self._read_chunked(amt)
  File "/usr/lib/python2.7/httplib.py", line 590, in _read_chunked
    value.append(self._safe_read(chunk_left))
  File "/usr/lib/python2.7/httplib.py", line 649, in _safe_read
    raise IncompleteRead(''.join(s), amt)
IncompleteRead: IncompleteRead(6492 bytes read, 9894 more expected)
```

Error happens frequently. Find out what causes this.

**Comment by bsyu1125** [comment]
It's a gspread issue. Doesn't cause any real problems, the script can recover from it (no duplicates or any bad behavior)
