### ISSUE TITLE
Traceback errors: HTTP errors

### ISSUE THREAD

**Issue by bsyu1125** [SLUGIS/incidentSpreadsheet#11]
```
Traceback (most recent call last):
  File "send.py", line 120, in <module>
    main()
  File "send.py", line 115, in main
    updateRow(wks, row, entry)
  File "send.py", line 75, in updateRow
    wks.insert_row(row, rowNum+1)
  File "/usr/local/lib/python2.7/dist-packages/gspread/models.py", line 562, in insert_row
    newcell = self.cell(r + (index - 1), c)
  File "/usr/local/lib/python2.7/dist-packages/gspread/models.py", line 323, in cell
    self._cell_addr(row, col))
  File "/usr/local/lib/python2.7/dist-packages/gspread/client.py", line 262, in get_cells_cell_id_feed
    r = self.session.get(url)
  File "/usr/local/lib/python2.7/dist-packages/gspread/httpsession.py", line 79, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gspread/httpsession.py", line 75, in request
    raise HTTPError(response)
HTTPError

```
Happens often, find out what causes this

**Comment by bsyu1125** [comment]
It's a gspread issue. Doesn't cause any real problems, the script can recover from it (no duplicates or any bad behavior)
